### ISSUE TITLE
Unable to get instances from Sql Server Browser on host

### ISSUE THREAD

**Issue by mnadeem** [denisenkom/go-mssqldb#643]
**Describe the bug**

1) 
URL
`sqlserver://user:pass@server.ms.ds.org.com:1433/db`

Error

`Unable to get instances from Sql Server Browser on host server.ms.ds.org.com: read udp 10.130.129.181:53997->10.204.74.47:1434: read: connection refused`

2) How to specify the password in url if it contains `@`

### Further technical details
SQL Server version: Microsoft SQL Server 2014 (SP3-CU4-GDR) (KB4583462) - 12.0.6433.1 (X64) 
	Oct 31 2020 02:54:45 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

**Additional context**

**Comment by robinknaapen** [comment]
This should work fine, tested with the docker-compose.yml below 

```Go
package main

import (
	"database/sql"

	_ "github.com/denisenkom/go-mssqldb"
)

func main() {
	db, err := sql.Open(`sqlserver`, `sqlserver://sa:P@ssw0rd@localhost:14330?database=master`)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	err = db.Ping()
	if err != nil {
		panic(err)
	}
}
```

```yaml
version: "2.1"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 14330:1433
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'P@ssw0rd' -Q 'select 1'"]
      interval: 3s
      timeout: 5s
      retries: 5
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=Express
```
